key-master:
  build: .
  links:
   - dynamodb
  ports:
    - "1337:1337"
  environment:
    ENV: "DEV"
  volumes:
    - .:/usr/src/app/
  entrypoint: "/usr/src/app/run-local.sh"
dynamodb:
  image: fitz/dynamodb-local
  ports:
  - "8000:8000"
  command: fitz/dynamodb-local -sharedDb
